name: 'Pull request copy to another repo'
description: 'Copies files (directories or entire branch) to a new branch of another repo and raises a PR'
inputs:
  source_folder:
    description: 'Source folder from origin'
    required: true
  destination_repo:
    description: 'Destination repository'
    required: true
  destination_owner:
    description: 'Destination owner'
    required: true
  destination_folder:
    description: 'Destination folder to push the origin folder'
    required: false
  user_email:
    description: 'Email for the git commit'
    required: false
  user_name:
    description: 'GitHub username for the commit'
    required: false
  destination_base_branch:
    description: 'The branch into which you want your code merged.'
    required: false
    default: "main"
  files_to_remove_path:
    description: 'Relative file path including list of files to not include in PR'
    required: false
    default: ".github/workflows/ci_ignore.txt"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.source-folder }}
    - ${{ inputs.destination-repo }}
    - ${{ inputs.destination-owner }}
    - ${{ inputs.destination-folder }}
    - ${{ inputs.user-email }}
    - ${{ inputs.user-name }}
    - ${{ inputs.destination-base-branch }}
    - ${{ inputs.files-to-remove-path }}
branding:
  icon: 'git-commit'
  color: 'green'
